edition = "2023";

package examplepb.oneof;

import "validate/validate.proto";

enum MyEnum {
    a = 0;
    b = 1;
}

message TestOneOf {
  message Msg1 {}
  message Msg2 {}
  message Msg3 {}
  message Location {
    double lat = 1 [(validate.rules).double = {gte: -90,  lte: 90}];
    double lng = 2 [(validate.rules).double = {gte: -180, lte: 180}];
  }

  oneof test_oneof {
    option (validate.required) = true;
    Msg1 msg1 = 1;
    Msg2 msg2 = 2;
    Msg3 msg3 = 3;
    MyEnum my_enum = 4;
    Location loc = 5;
  }
}
